### Regis University

**MSDS688_X70: Artificial Intelligence**  
Master of Science in Data Science Program

#### Week 5: Building Conversational Bots  
*GPU Required*

## Lecture: Week 5 - Building Conversational Bots with DialoGPT

### Overview

This week, we focus on building conversational chatbots using **DialoGPT**. DialoGPT is a conversational model developed by Microsoft, based on GPT-2, that is fine-tuned specifically for dialogue generation. In this lecture, we will discuss how DialoGPT works, how it can be fine-tuned for custom conversational tasks, how chatbots function from an engineering perspective, and how to build a chatbot capable of generating human-like responses.

---

### 1. **How Chatbots Work**

Chatbots are AI-powered systems designed to simulate human conversations. From a technical perspective, chatbots are built using a combination of machine learning algorithms, natural language processing (NLP), and sometimes rule-based systems. Below is a breakdown of how modern chatbots are engineered:

#### Key Components of a Chatbot:
- **Natural Language Understanding (NLU)**: This component helps the chatbot understand user inputs. It involves breaking down user queries into structured data, extracting the intent (what the user wants), and identifying entities (specific pieces of information like dates, names, or locations).
- **Response Generation**: This can be either rule-based (predefined responses) or based on machine learning models. Models like **DialoGPT** generate responses dynamically by predicting the next words in the conversation.
- **Dialogue Management**: This component manages the flow of conversation, deciding how the chatbot should respond based on the context. It ensures that the conversation stays coherent and follows a logical sequence.
- **Backend APIs and Integrations**: Chatbots often need to integrate with backend systems (e.g., databases, APIs) to retrieve information or complete tasks like booking a ticket or checking account balances.

#### Types of Chatbots:
1. **Rule-Based Chatbots**: These rely on predefined rules and responses, often using decision trees or simple pattern matching to guide the conversation.
2. **AI-Based Chatbots**: These use machine learning models to generate responses. They are more flexible and can handle a wider range of queries but require large amounts of data for training.
3. **Hybrid Chatbots**: These combine rule-based systems with AI, allowing the chatbot to handle simple queries through predefined rules and more complex queries through machine learning.

#### Key Challenges in Building Chatbots:
- **Understanding Ambiguity**: User inputs can often be ambiguous, making it difficult for the chatbot to understand the exact intent.
- **Maintaining Context**: Chatbots need to remember and maintain the context of the conversation across multiple turns.
- **Response Coherence**: Generating relevant and coherent responses is challenging, especially in long conversations.
- **Scalability**: Chatbots need to handle thousands of interactions simultaneously while maintaining performance.

---

### 2. **How DialoGPT Works**

#### DialoGPT Overview:
**DialoGPT** is a variant of GPT-2, fine-tuned for conversational AI tasks. It is designed to generate coherent, context-aware responses in a dialogue format. Like GPT-2, DialoGPT uses a **transformer-based** architecture with a **decoder-only** structure, meaning it predicts the next token in a sequence based on all the preceding tokens.

#### Key Concepts:
- **Pretraining on Conversations**: DialoGPT is pretrained on large conversational datasets, which allows it to generate contextually relevant responses.
- **Unidirectional Decoder**: Similar to GPT-2, DialoGPT generates text left-to-right, predicting the next word based on the conversation so far.
- **Self-Attention**: DialoGPT uses self-attention mechanisms to focus on relevant parts of the conversation when generating responses.

#### How DialoGPT Generates Dialogue:
1. **Input Tokenization**: The conversation is tokenized into smaller units (tokens) and fed into the model.
2. **Context-Aware Response Generation**: The model generates the next token based on the entire conversation history. This allows it to maintain context and coherence over multiple turns in a conversation.
3. **Text Generation**: The generated tokens are decoded back into human-readable text, forming the chatbot’s response.

---

### 3. **Fine-Tuning DialoGPT**

Fine-tuning allows us to customize DialoGPT to respond better in specific conversational contexts. This involves training the model on a custom dataset, which may include dialogues from a particular domain (e.g., customer support, therapy, or informal chats).

#### Steps for Fine-Tuning DialoGPT:
1. **Load Pretrained Model**: Start with a pretrained DialoGPT model (e.g., `microsoft/DialoGPT-medium`).
2. **Prepare the Dataset**: Use a dialogue dataset like **DailyDialog**. Tokenize the conversations so they can be fed into the model.
3. **Train the Model**: Fine-tune DialoGPT on the dataset by training it to predict the next token in each dialogue sequence. Adjust the learning rate and training parameters to fit the dataset size.
4. **Evaluation**: After fine-tuning, evaluate the chatbot’s performance by generating responses and comparing them to the expected dialogue or using metrics like **perplexity**.

#### Tokenization and Training:
- **Tokenization**: The input conversations are tokenized into sequences of tokens. Since dialogues can vary in length, padding may be necessary to ensure the sequences have the same length.
- **Training Objective**: The training process involves predicting the next word in a conversation based on the context provided by the previous words.

#### Fine-Tuning Parameters:
- **Learning Rate**: Controls how quickly the model adjusts its weights during training.
- **Epochs**: The number of times the model goes through the training dataset.
- **Batch Size**: The number of samples the model processes before updating its weights.

---

### 4. **Building a Chatbot with DialoGPT**

Once fine-tuned, DialoGPT can be used to build a fully functional chatbot. The chatbot can generate responses to user inputs based on the conversational context, providing coherent and contextually relevant replies.

#### Response Generation:
- **Max and Min Length**: Control the length of the chatbot’s responses. Setting a minimum length ensures the responses are not too short, while a maximum length prevents overly long replies.
- **Temperature**: Adjusts the randomness of the model’s predictions. Higher temperatures make the chatbot more creative, while lower temperatures make the chatbot more deterministic.
- **Top-p (Nucleus Sampling)**: Controls the diversity of the generated responses by sampling from the most probable words until the cumulative probability reaches `p` (e.g., 0.9).

#### Interaction with the Chatbot:
After fine-tuning, you can start a conversation with the chatbot by feeding it input text. The chatbot will generate responses based on its training and the provided input. The conversation history is stored and fed back into the model, allowing the chatbot to maintain context across multiple dialogue turns.

```python
# Example of chatting with the fine-tuned model
def chat_with_model(model, tokenizer):
    chat_history_ids = None
    while True:
        user_input = input("User: ")
        new_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors='pt').to(device)

        # Concatenate the new input with previous chat history
        bot_input_ids = torch.cat([chat_history_ids, new_input_ids], dim=-1) if chat_history_ids is not None else new_input_ids

        # Generate the response
        chat_history_ids = model.generate(
            bot_input_ids,
            max_length=1000,
            min_length=10,
            no_repeat_ngram_size=3,
            temperature=0.7,
            top_p=0.9,
            pad_token_id=tokenizer.eos_token_id
        )

        # Decode and print the response
        bot_response = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
        print(f"Chatbot: {bot_response}")
```

#### Controlling the Chatbot’s Behavior:
- **No Repeat N-Gram Size**: Prevents the chatbot from repeating phrases or sentences by ensuring that no n-grams (sequences of words) are repeated within the generated response.
- **Attention Masking**: Helps the model focus on relevant tokens in the input sequence when generating responses.

---

### 5. **Challenges in Building Conversational Bots**

While building conversational bots with models like DialoGPT is powerful, there are several challenges to consider:
- **Understanding Ambiguity**: User inputs can often be ambiguous, making it difficult for the chatbot to understand the exact intent.
- **Maintaining Context**: Chatbots need to remember and maintain the context of the conversation across multiple turns.
- **Response Coherence**: Generating relevant and coherent responses is challenging, especially in long conversations.
- **Domain Adaptation**: Fine-tuning the model on specific datasets can help adapt the chatbot to particular domains, but it may still struggle with out-of-domain inputs.
- **Ethical Considerations**: Conversational bots can generate inappropriate or biased content. It is important to monitor and filter chatbot outputs for ethical and responsible AI use.

---

### Conclusion

This week’s assignment focuses on fine-tuning **DialoGPT** to create a conversational chatbot capable of generating human-like responses. By fine-tuning the model on a custom dataset, adjusting response generation parameters, and evaluating the chatbot’s performance, you will gain insights into the process of building conversational AI systems. Pay attention to the hyperparameters that control response generation, such as temperature, top-p, and n-gram size, as these will have a significant impact on the chatbot’s behavior.

---

## Assignment Part 1: Follow Me – Fine-Tuning DialoGPT with Custom Dataset

In this section, you will fine-tune the DialoGPT model using a custom dataset to build a conversational chatbot. You will learn how to prepare and fine-tune a model designed for conversational AI and test its ability to generate human-like responses.

In [1]:
# --- Original install (commented out) ---
# On current Colab, latest transformers silently breaks DialoGPT's lm_head
# weight tying so fine-tuning produces pure garbage output. We pin to a known
# working 4.x release. After running this cell once, do
#     Runtime -> Restart session
# and then run from the top.
# !pip install transformers datasets torch

# --- Replacement: pinned versions ---
!pip install -q "transformers==4.46.3" "datasets==2.21.0" torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.1/44.1 kB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 84.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.3/527.3 kB 33.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.6/177.6 kB 16.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 34.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 62.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.6.1 which is incompatible.

In [2]:
from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
from datasets import load_dataset
import torch

In [3]:
# Load the pre-trained DialoGPT model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

config.json:   0%|          | 0.00/642 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/863M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [4]:
# Set the pad_token to eos_token for padding
tokenizer.pad_token = tokenizer.eos_token

In [5]:
# Load and prepare a conversational dataset for fine-tuning
#
# --- Original (commented out) ---
# The upstream daily_dialog loader is a Python script whose zip-handling code
# is broken on current datasets versions (NotADirectoryError on train.zip).
# We swap to OpenRL/daily_dialog — a pure-parquet mirror with the same
# dialog/act/emotion schema, no script execution required.
# dataset = load_dataset("daily_dialog")

dataset = load_dataset("OpenRL/daily_dialog")

Downloading readme:   0%|          | 0.00/892 [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/3.61M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/334k [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/331k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/11118 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [6]:
# Use a smaller subset (e.g., first 100 samples)
small_train_dataset = dataset['train'].select(range(100))

In [7]:
# --- Original tokenize_function (commented out) ---
# The original joined a whole dialog with spaces and set labels=input_ids
# everywhere, which trains the model to predict every token including ~450
# padding positions per row. That collapses the lm_head. The replacement
# formats each dialog as alternating User:/Bot: turns and masks everything
# except the bot's responses with -100, matching the Part 2 fix exactly.
#
# def tokenize_function(examples):
#     joined_dialogs = [" ".join(dialog) for dialog in examples["dialog"]]
#     return tokenizer(joined_dialogs, truncation=True, padding="max_length", max_length=512)

# --- Replacement: label-masked, role-formatted tokenization ---
MAX_LENGTH_P1 = 256

def tokenize_function(example):
    dialog = example['dialog']  # list of turns, alternating user (even) / bot (odd)

    segments = []
    for i, line in enumerate(dialog):
        line = line.strip()
        if i % 2 == 0:
            segments.append((f"User: {line}\n", False))
        else:
            segments.append((f"Bot: {line}{tokenizer.eos_token}", True))

    input_ids, labels = [], []
    for text, is_bot in segments:
        ids = tokenizer.encode(text, add_special_tokens=False)
        input_ids.extend(ids)
        labels.extend(ids if is_bot else [-100] * len(ids))

    input_ids = input_ids[:MAX_LENGTH_P1]
    labels = labels[:MAX_LENGTH_P1]

    pad_len = MAX_LENGTH_P1 - len(input_ids)
    attention_mask = [1] * len(input_ids) + [0] * pad_len
    input_ids = input_ids + [tokenizer.pad_token_id] * pad_len
    labels = labels + [-100] * pad_len

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'labels': labels,
    }

In [8]:
# --- Original (commented out) ---
# The original passed batched=True, but our new tokenize_function takes a
# single example, not a batch. We also let HF Datasets figure out which
# columns to drop so this works across slightly different schemas.
# tokenized_dataset = small_train_dataset.map(
#     tokenize_function, batched=True,
#     remove_columns=["dialog", "act", "emotion"],
# )

# --- Replacement: per-example map ---
tokenized_dataset = small_train_dataset.map(
    tokenize_function,
    remove_columns=small_train_dataset.column_names,
)

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

In [9]:
# Define the data collator
from transformers import DataCollatorForLanguageModeling, default_data_collator

In [10]:
# --- Original collator (commented out) ---
# DataCollatorForLanguageModeling(mlm=False) overwrites the labels field
# with a copy of input_ids, which undoes our label masking. Swap it for
# default_data_collator which just stacks tensors as-is.
# data_collator = DataCollatorForLanguageModeling(
#     tokenizer=tokenizer,
#     mlm=False,
# )

data_collator = default_data_collator

In [11]:
# --- Original TrainingArguments (commented out) ---
# training_args = TrainingArguments(
#     output_dir='./results',
#     num_train_epochs=1,
#     per_device_train_batch_size=2,
#     save_steps=1000,
#     save_total_limit=2,
#     learning_rate=5e-5,
#     logging_dir='./logs',
#     logging_steps=100,
# )

# --- Replacement ---
# More epochs because label masking means only ~15% of tokens contribute to
# loss. save_strategy='no' avoids intermediate checkpoint spam. report_to='none'
# silences W&B / TensorBoard.
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=2,
    save_strategy='no',
    learning_rate=5e-5,
    logging_dir='./logs',
    logging_steps=10,
    report_to='none',
)

In [12]:
# Define the Trainer for fine-tuning the model
trainer = Trainer(
    model=model,  # The pre-trained model to fine-tune
    args=training_args,  # Training arguments defined above
    train_dataset=tokenized_dataset,  # The smaller dataset used for training
    data_collator=data_collator,  # Use the data collator to create labels
)

In [13]:
# Fine-tune the model
trainer.train()

TrainOutput(global_step=150, training_loss=2.2409462610880535, metrics={'train_runtime': 71.2604, 'train_samples_per_second': 4.21, 'train_steps_per_second': 2.105, 'total_flos': 139305104179200.0, 'train_loss': 2.2409462610880535, 'epoch': 3.0})

In [14]:
# Save the fine-tuned model
model.save_pretrained("./fine_tuned_chatbot")
tokenizer.save_pretrained("./fine_tuned_chatbot")

('./fine_tuned_chatbot/tokenizer_config.json',
 './fine_tuned_chatbot/special_tokens_map.json',
 './fine_tuned_chatbot/vocab.json',
 './fine_tuned_chatbot/merges.txt',
 './fine_tuned_chatbot/added_tokens.json',
 './fine_tuned_chatbot/tokenizer.json')

In [15]:
# Move the model to the GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

In [16]:
# --- Original interactive chat_with_model (commented out) ---
# The input() loop is fragile in Colab (a CUDA error inside it poisons the
# context and the only fix is a runtime restart). The sampling params
# (max_length=1000, min_length=10, top_p=0.9) could also intersect to mask
# all candidate tokens, making torch.multinomial fire a device-side assert.
#
# def chat_with_model(model, tokenizer):
#     chat_history_ids = None
#     while True:
#         user_input = input("You: ")
#         if user_input.lower() == "exit":
#             print("Chatbot: Goodbye!")
#             break
#         new_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors='pt').to(device)
#         bot_input_ids = torch.cat([chat_history_ids, new_input_ids], dim=-1) if chat_history_ids is not None else new_input_ids
#         chat_history_ids = model.generate(bot_input_ids, max_length=1000, ..., do_sample=True)
#         bot_response = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
#         print(f"Chatbot: {bot_response}")

# --- Replacement: scripted_chat_p1 (greedy, User:/Bot: format) ---
# Runs a fixed list of user messages against the fine-tuned model. No input()
# loop, greedy decoding, prompt format matches what we trained on.
def scripted_chat_p1(model, tokenizer, user_messages):
    history = ""
    for user_input in user_messages:
        print(f"You: {user_input}")
        history += f"User: {user_input}\nBot:"

        input_ids = tokenizer.encode(history, return_tensors='pt').to(device)
        attention_mask = torch.ones_like(input_ids)

        with torch.no_grad():
            output_ids = model.generate(
                input_ids,
                attention_mask=attention_mask,
                max_new_tokens=60,
                min_new_tokens=3,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id,
                no_repeat_ngram_size=3,
                repetition_penalty=1.1,
                do_sample=False,        # GREEDY — no multinomial
            )

        new_tokens = output_ids[0, input_ids.shape[-1]:]
        bot_response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
        if 'User:' in bot_response:
            bot_response = bot_response.split('User:')[0].strip()
        if not bot_response:
            bot_response = "(no response)"

        print(f"Bot: {bot_response}\n")
        history += f" {bot_response}{tokenizer.eos_token}"

In [17]:
# --- Original interactive call (commented out) ---
# chat_with_model(model, tokenizer)

# --- Replacement: scripted conversation ---
scripted_chat_p1(
    model,
    tokenizer,
    [
        "Hi, how are you?",
        "What do you like to do for fun?",
        "Tell me something interesting.",
    ],
)

You: Hi, how are you?
Bot: I'm good, thanks. How about you?

You: What do you like to do for fun?
Bot: Well, I like playing tennis and playing with friends.

You: Tell me something interesting.
Bot: Sure, I like to play basketball.

## Assignment Part 2: Your Turn – Training Your Own Chatbot with Persona Chat

In this section, you will train your own chatbot using the provided framework and dataset. You will explore how adjusting different hyperparameters and training data can influence the quality of the bot's responses. **A framework has been provided, and your job is to complete the TODOs.**

In [18]:
# --- Original Part 2 imports (commented out) ---
# from transformers import AutoModelForCausalLM, AutoTokenizer, Trainer, TrainingArguments
# from transformers import DataCollatorForLanguageModeling
# import torch
# import pandas as pd
# import random

# --- Replacement: add default_data_collator (we use it instead of the LM collator) ---
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    Trainer,
    TrainingArguments,
    default_data_collator,
)
import torch
import pandas as pd
import random

In [19]:
# Load the pre-trained DialoGPT model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-medium")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-medium")

In [20]:
# Set the pad_token to eos_token for padding
tokenizer.pad_token = tokenizer.eos_token

In [21]:
# Load persona-chat data from the CSV file
personality_data = pd.read_csv('personality.csv')

In [22]:
# Use a subset of the data
personality_data_subset = personality_data.head(100)

In [23]:
## TODO: Tokenize the dataset ##
#
# --- Original (commented out) ---
# The naive version built input_ids covering persona + full chat and then set
# labels = input_ids everywhere. That meant the model was trained to predict
# persona text, user questions, AND ~90% padding tokens — the gradient signal
# was dominated by noise and the lm_head collapsed.
#
# def tokenize_function(row):
#     ## TODO: Combine persona and chat columns to form input sequences ##
#     input_text = str(row["Persona"]) + tokenizer.eos_token + str(row["chat"])
#     return tokenizer(
#         input_text,
#         truncation=True,
#         padding="max_length",
#         max_length=512,
#     )

# --- Replacement: label-masked, role-formatted tokenization ---
# Format each row as:
#   Persona: <persona>\nUser: <u1>\nBot: <b1><eos>User: <u2>\nBot: <b2><eos>...
# Then build a `labels` array where every token that is NOT part of a Bot turn
# gets set to -100 (PyTorch's ignore_index). The model only learns to produce
# bot responses; persona text, user questions, and padding are ignored by the
# loss. This is the critical fix — without it the model collapses.
MAX_LENGTH = 256

def tokenize_function(row):
    persona = str(row['Persona']).strip()
    chat_lines = [l.strip() for l in str(row['chat']).split('\n') if l.strip()]

    # Build (text, is_bot) segments. Even-indexed chat lines = user, odd = bot.
    segments = [(f"Persona: {persona}\n", False)]
    for i, line in enumerate(chat_lines):
        if i % 2 == 0:
            segments.append((f"User: {line}\n", False))
        else:
            segments.append((f"Bot: {line}{tokenizer.eos_token}", True))

    input_ids, labels = [], []
    for text, is_bot in segments:
        ids = tokenizer.encode(text, add_special_tokens=False)
        input_ids.extend(ids)
        labels.extend(ids if is_bot else [-100] * len(ids))

    # Truncate
    input_ids = input_ids[:MAX_LENGTH]
    labels = labels[:MAX_LENGTH]

    # Pad to fixed length; padding is also masked out of the loss.
    pad_len = MAX_LENGTH - len(input_ids)
    attention_mask = [1] * len(input_ids) + [0] * pad_len
    input_ids = input_ids + [tokenizer.pad_token_id] * pad_len
    labels = labels + [-100] * pad_len

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'labels': labels,
    }

In [24]:
# Apply tokenization to the subset of data and store the results in a list
tokenized_inputs = [tokenize_function(row) for _, row in personality_data_subset.iterrows()]

In [25]:
# --- Original CustomDataset (commented out) ---
# The original set labels = a copy of input_ids in __getitem__, which
# undoes the label masking we did in tokenize_function. We need to carry
# the precomputed 'labels' list through instead.
#
# class CustomDataset(torch.utils.data.Dataset):
#     def __init__(self, tokenized_data):
#         self.input_ids = [data['input_ids'] for data in tokenized_data]
#         self.attention_mask = [data['attention_mask'] for data in tokenized_data]
#
#     def __len__(self):
#         return len(self.input_ids)
#
#     def __getitem__(self, idx):
#         return {
#             'input_ids': torch.tensor(self.input_ids[idx]),
#             'attention_mask': torch.tensor(self.attention_mask[idx]),
#             'labels': torch.tensor(self.input_ids[idx])  # <- the bug
#         }

# --- Replacement: store and return precomputed labels ---
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, tokenized_data):
        self.input_ids = [d['input_ids'] for d in tokenized_data]
        self.attention_mask = [d['attention_mask'] for d in tokenized_data]
        self.labels = [d['labels'] for d in tokenized_data]

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return {
            'input_ids': torch.tensor(self.input_ids[idx], dtype=torch.long),
            'attention_mask': torch.tensor(self.attention_mask[idx], dtype=torch.long),
            'labels': torch.tensor(self.labels[idx], dtype=torch.long),
        }

In [26]:
# Create a custom dataset from the tokenized inputs
dataset = CustomDataset(tokenized_inputs)

In [27]:
# --- Original collator (commented out) ---
# DataCollatorForLanguageModeling(mlm=False) overwrites the `labels` field
# with a copy of input_ids, which undoes the label masking we did in
# tokenize_function. We swap it for default_data_collator which just stacks
# the tensors as-is without touching labels.
#
# data_collator = PadMaskingCollator(
#     tokenizer=tokenizer,
#     mlm=False,
# )

# --- Replacement ---
data_collator = default_data_collator

In [28]:
## TODO: Define the training arguments ##
#
# --- Previous version (commented out) ---
# training_args = TrainingArguments(
#     output_dir='./results_part2',
#     num_train_epochs=1,
#     per_device_train_batch_size=2,
#     save_steps=1000,
#     save_total_limit=2,
#     learning_rate=5e-5,
#     logging_dir='./logs_part2',
#     logging_steps=10,
# )

# --- Replacement ---
# - num_train_epochs=3: only ~10% of tokens contribute to loss (we masked the
#   rest), so we need more passes to actually learn the bot's turns.
# - save_strategy='no': we save manually after training, no need for Trainer
#   to scatter intermediate checkpoints.
# - report_to='none': silences the Weights & Biases / TensorBoard nag.
training_args = TrainingArguments(
    output_dir='./results_part2',
    num_train_epochs=3,
    per_device_train_batch_size=2,
    save_strategy='no',
    learning_rate=5e-5,
    logging_dir='./logs_part2',
    logging_steps=10,
    report_to='none',
)

In [30]:
## TODO: Define the Trainer for fine-tuning the model ##
trainer = Trainer(
    model=model,                  # The pre-trained DialoGPT-medium to fine-tune
    args=training_args,           # Training config from the previous cell
    train_dataset=dataset,        # CustomDataset wrapping our label-masked rows
    data_collator=data_collator,  # default_data_collator — preserves our labels as-is
)

In [31]:
# Fine-tune the model
trainer.train()

TrainOutput(global_step=150, training_loss=2.487336247762044, metrics={'train_runtime': 77.2765, 'train_samples_per_second': 3.882, 'train_steps_per_second': 1.941, 'total_flos': 139305104179200.0, 'train_loss': 2.487336247762044, 'epoch': 3.0})

In [32]:
# Save the fine-tuned model
model.save_pretrained("./custom_fine_tuned_chatbot")
tokenizer.save_pretrained("./custom_fine_tuned_chatbot")

('./custom_fine_tuned_chatbot/tokenizer_config.json',
 './custom_fine_tuned_chatbot/special_tokens_map.json',
 './custom_fine_tuned_chatbot/vocab.json',
 './custom_fine_tuned_chatbot/merges.txt',
 './custom_fine_tuned_chatbot/added_tokens.json',
 './custom_fine_tuned_chatbot/tokenizer.json')

In [33]:
# Move the model to the GPU if available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

In [34]:
# --- Previous get_single_response (commented out) ---
# The old version joined persona and question with a space. Now that we train
# the model on an explicit Persona:/User:/Bot: format, we have to prompt it
# the same way at inference or it won't know what to produce.
#
# def get_single_response(model, tokenizer, question, persona):
#     input_text = persona + " " + question
#     inputs = tokenizer(input_text + tokenizer.eos_token, return_tensors='pt', padding=True).to(device)
#     output_ids = model.generate(
#         inputs['input_ids'],
#         attention_mask=inputs['attention_mask'],
#         max_new_tokens=60,
#         min_new_tokens=5,
#         pad_token_id=tokenizer.eos_token_id,
#         no_repeat_ngram_size=3,
#         repetition_penalty=1.1,
#         do_sample=False,
#     )
#     response = tokenizer.decode(output_ids[:, inputs['input_ids'].shape[-1]:][0], skip_special_tokens=True)
#     return response.strip()

# --- Replacement: matches training format ---
def get_single_response(model, tokenizer, question, persona):
    prompt = f"Persona: {persona}\nUser: {question}\nBot:"
    input_ids = tokenizer.encode(prompt, return_tensors='pt').to(device)
    attention_mask = torch.ones_like(input_ids)

    with torch.no_grad():
        output_ids = model.generate(
            input_ids,
            attention_mask=attention_mask,
            max_new_tokens=60,
            min_new_tokens=3,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            no_repeat_ngram_size=3,
            repetition_penalty=1.1,
            do_sample=False,        # GREEDY — no multinomial
        )

    response = tokenizer.decode(
        output_ids[0, input_ids.shape[-1]:],
        skip_special_tokens=True,
    ).strip()
    # Stop at the next User: turn if the model tried to continue past its reply
    if 'User:' in response:
        response = response.split('User:')[0].strip()
    return response

# Test with a single question and persona
persona_example = "I love cooking and exploring new recipes."
question_example = "What is your favorite dish to cook?"

response = get_single_response(model, tokenizer, question_example, persona_example)
print(f"Question: {question_example}")
print(f"Chatbot: {response}")

Question: What is your favorite dish to cook?
Chatbot: I like to cook my own food.

In [35]:
# --- Original interactive chat_with_model (commented out earlier) ---
# The input() loop is fragile in Colab and the old decoding params caused
# CUDA multinomial asserts. See earlier notes.
#
# def chat_with_model(model, tokenizer, personality_data):
#     persona = random.choice(personality_data['Persona'])
#     print(f"Chatbot's Persona: {persona}")
#     chat_history_ids = None
#     while True:
#         user_input = input("You: ")
#         if user_input.lower() == "exit":
#             print("Chatbot: Goodbye!")
#             break
#         persona_input = persona + " " + user_input
#         new_input_ids = tokenizer.encode(persona_input + tokenizer.eos_token, return_tensors='pt').to(device)
#         bot_input_ids = torch.cat([chat_history_ids, new_input_ids], dim=-1) if chat_history_ids is not None else new_input_ids
#         chat_history_ids = model.generate(bot_input_ids, max_new_tokens=60, ...)
#         bot_response = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
#         print(f"Chatbot: {bot_response}")

# --- Replacement: scripted_chat_p2 (greedy, Persona:/User:/Bot: format) ---
# Runs a fixed list of user messages against a given persona. No input() loop,
# greedy decoding, prompt format matches training exactly.
def scripted_chat_p2(model, tokenizer, user_messages, persona):
    print(f"Persona: {persona}\n")
    history = f"Persona: {persona}\n"

    for user_input in user_messages:
        print(f"You: {user_input}")
        history += f"User: {user_input}\nBot:"

        input_ids = tokenizer.encode(history, return_tensors='pt').to(device)
        attention_mask = torch.ones_like(input_ids)

        with torch.no_grad():
            output_ids = model.generate(
                input_ids,
                attention_mask=attention_mask,
                max_new_tokens=60,
                min_new_tokens=3,
                pad_token_id=tokenizer.eos_token_id,
                eos_token_id=tokenizer.eos_token_id,
                no_repeat_ngram_size=3,
                repetition_penalty=1.1,
                do_sample=False,
            )

        new_tokens = output_ids[0, input_ids.shape[-1]:]
        bot_response = tokenizer.decode(new_tokens, skip_special_tokens=True).strip()
        if 'User:' in bot_response:
            bot_response = bot_response.split('User:')[0].strip()
        if not bot_response:
            bot_response = "(no response)"

        print(f"Bot: {bot_response}\n")
        history += f" {bot_response}{tokenizer.eos_token}"

In [36]:
# --- Original interactive call (commented out) ---
# chat_with_model(model, tokenizer, personality_data)

# --- Replacement: scripted persona-grounded conversation ---
random.seed(42)
persona = random.choice(personality_data['Persona'].tolist()).strip()

scripted_chat_p2(
    model,
    tokenizer,
    [
        "Hi, how are you?",
        "What do you like to do for fun?",
        "Tell me something interesting about yourself.",
    ],
    persona=persona,
)

Persona: i just started college. i have 3 science classes. i work part time in the campus library. i am living at home but hope to live in the dorms next year.

You: Hi, how are you?
Bot: i am doing great, just finished my first semester of college.

You: What do you like to do for fun?
Bot: reading, watching tv, playing video games, and going out with friends.

You: Tell me something interesting about yourself.
Bot: nothing too interesting. what kind of school do you want to go to?